import React,{useEffect,useMemo,useState} from 'react'
import {Archive,CheckCircle2,Database,History,KeyRound,LoaderCircle,Package,RefreshCw,Save,ShieldCheck,Trash2,Wifi,XCircle} from 'lucide-react'
import {DeleteCatalogItem,GetBackupStatus,GetBitzConfig,GetCommercialConfig,ListCatalog,ListRooms,RoomHistory,RunBackup,SaveBitzConfig,SaveCommercialConfig,TestBitzAccess,UpdateRoom} from '../wailsjs/go/main/App'

const statuses=[['DISPONIVEL','Disponível'],['LIMPO_DESFORRADO','Limpo, mas desforrado'],['MANUTENCAO_LIMPEZA','Manutenção de limpeza'],['SAIDA_ENTRADA','Saída e entrada'],['ENTRADA','Entrada'],['SAIDA','Saída'],['INTERDITADO','Interditado'],['LIMPAR','Limpar']]

export default function AssistantOps({notify}){
 const [tab,setTab]=useState('rooms'),[busy,setBusy]=useState(false),[rooms,setRooms]=useState([]),[selected,setSelected]=useState(null),[history,setHistory]=useState([]),[commercial,setCommercial]=useState({Mode:'disabled',Allowlist:[],GroupPhone:'5573988240413',FinalMessage1:'',FinalMessage2:''}),[bitz,setBitz]=useState(null),[testPhone,setTestPhone]=useState(''),[catalog,setCatalog]=useState([]),[backup,setBackup]=useState(null)
 const run=async fn=>{setBusy(true);try{return await fn()}catch(e){notify(String(e),'error')}finally{setBusy(false)}}
 const loadRooms=()=>run(async()=>setRooms(await ListRooms()||[]))
 const loadCommercial=()=>run(async()=>{setCommercial(await GetCommercialConfig());setBitz(await GetBitzConfig())})
 const loadCatalog=()=>run(async()=>setCatalog(await ListCatalog()||[]))
 const loadBitz=()=>run(async()=>setBitz(await GetBitzConfig()))
 const loadBackup=()=>run(async()=>setBackup(await GetBackupStatus()))
 useEffect(()=>{loadRooms()},[])
 const counts=useMemo(()=>rooms.reduce((m,r)=>({...m,[r.Status]:(m[r.Status]||0)+1}),{}),[rooms])
 const choose=room=>run(async()=>{setSelected({...room});setHistory(await RoomHistory(room.Number)||[])})
 const saveRoom=()=>run(async()=>{await UpdateRoom({Number:selected.Number,Guests:Number(selected.Guests||0),Status:selected.Status,Note:selected.Note||''});notify(`Quarto ${selected.Number} atualizado`);await loadRooms();setSelected(null)})
 const saveCommercial=()=>run(async()=>{await SaveCommercialConfig(commercial);notify('Atendimento comercial atualizado');await loadCommercial()})
 const saveBitz=enabled=>run(async()=>{await SaveBitzConfig({...bitz,Enabled:enabled});notify(enabled?'Integração Bitz salva e ativada':'Integração Bitz desativada');setBitz(await GetBitzConfig())})
 const testBitz=()=>run(async()=>{await TestBitzAccess();notify('Acesso ao Bitz validado sem criar reserva')})
 const addTest=()=>{const n=testPhone.replace(/\D/g,'');if(!n)return;setCommercial({...commercial,Allowlist:[...(commercial.Allowlist||[]).filter(x=>x!==n),n]});setTestPhone('')}
 const changeTab=id=>{setTab(id);if(id==='rooms')loadRooms();if(id==='commercial')loadCommercial();if(id==='bitz')loadBitz();if(id==='catalog')loadCatalog();if(id==='backup')loadBackup()}
 return <div className="stack assistant-ops"><div className="page-intro"><div><span className="section-kicker">ASSISTENTE PARAÍSO</span><h2>Gestão operacional completa</h2><p>O mesmo estado usado pelos comandos do WhatsApp, agora administrado visualmente no Tino.</p></div>{busy&&<LoaderCircle className="spin"/>}</div>
  <div className="segmented"><button className={tab==='rooms'?'active':''} onClick={()=>changeTab('rooms')}>Quartos</button><button className={tab==='commercial'?'active':''} onClick={()=>changeTab('commercial')}>Comercial</button><button className={tab==='bitz'?'active':''} onClick={()=>changeTab('bitz')}>Pré-reserva Bitz</button><button className={tab==='catalog'?'active':''} onClick={()=>changeTab('catalog')}>Catálogo</button><button className={tab==='backup'?'active':''} onClick={()=>changeTab('backup')}>Backup e saúde</button></div>
  {tab==='rooms'&&<><div className="room-summary">{statuses.map(([id,label])=><div key={id} className={`room-stat status-${id.toLowerCase()}`}><b>{counts[id]||0}</b><span>{label}</span></div>)}</div><section className="panel room-board">{rooms.map(room=><button key={room.Number} className={`room-tile status-${room.Status.toLowerCase()}`} onClick={()=>choose(room)}><b>{room.Number}</b><span>{room.StatusLabel}</span>{room.Guests>0&&<small>{room.Guests} hóspede(s)</small>}{room.Note&&<em>{room.Note}</em>}</button>)}</section></>}
  {tab==='commercial'&&commercial&&<><div className="two-cards"><section className="panel"><div className="panel-icon"><Wifi/></div><h3>Modo de atendimento</h3><p>Controla imediatamente como contatos externos são atendidos pelo WhatsApp do Tino.</p><div className="mode-cards">{[['disabled','Desativado','Nenhum cliente recebe resposta automática.'],['test','Teste','Somente os números autorizados abaixo.'],['public','Público','Atendimento comercial ativo para contatos externos.']].map(([id,name,text])=><button key={id} className={commercial.Mode===id?'selected':''} onClick={()=>setCommercial({...commercial,Mode:id})}><b>{name}</b><span>{text}</span></button>)}</div></section><section className="panel"><h3>Números de teste</h3><p>Usados somente quando o modo Teste estiver ativo.</p><div className="inline-form"><input value={testPhone} onChange={e=>setTestPhone(e.target.value)} placeholder="Telefone com DDI"/><button className="secondary" onClick={addTest}>Adicionar</button></div><div className="chip-list">{(commercial.Allowlist||[]).map(n=><span key={n}>+{n}<button onClick={()=>setCommercial({...commercial,Allowlist:commercial.Allowlist.filter(x=>x!==n)})}>×</button></span>)}</div><div className="info-strip"><ShieldCheck/><span>Outros assuntos pausam a automação e mantêm a conversa não lida para o atendente.</span></div></section></div><section className="panel commercial-sequence"><div className="section-title"><div><h3>Fechamento do orçamento</h3><span>Enviado depois de todos os quartos e antes dos produtos do catálogo</span></div></div><div className="commercial-fields"><label className="field"><span>WhatsApp do setor de grupos</span><input value={commercial.GroupPhone||''} onChange={e=>setCommercial({...commercial,GroupPhone:e.target.value})} placeholder="5573988240413"/><small>Solicitações com mais de 6 quartos são encaminhadas para este número.</small></label><label className="field"><span>Mensagem final 1</span><textarea value={commercial.FinalMessage1||''} onChange={e=>setCommercial({...commercial,FinalMessage1:e.target.value})} placeholder="Primeira mensagem após os orçamentos"/></label><label className="field"><span>Mensagem final 2</span><textarea value={commercial.FinalMessage2||''} onChange={e=>setCommercial({...commercial,FinalMessage2:e.target.value})} placeholder="Segunda mensagem após os orçamentos"/></label></div><button className="primary wide" onClick={saveCommercial}><Save/>Salvar atendimento comercial</button></section></>}
  {tab==='catalog'&&<><section className="panel catalog-help"><Package/><div><h3>Produtos vinculados ao orçamento</h3><p>O cadastro continua seguro pelo WhatsApp: envie <b>configurar catálogo</b> e compartilhe um produto real do WhatsApp Business. Aqui você consulta e remove os vínculos.</p></div></section><div className="catalog-grid">{catalog.length?catalog.map(item=><article className="panel catalog-card" key={item.Category}><span className="tag ready">{item.Category}</span><h3>{item.Title}</h3><p>{item.Description||'Sem descrição'}</p><dl><dt>Product ID</dt><dd>{item.ProductID}</dd><dt>Proprietário</dt><dd>{item.Owner}</dd><dt>Preço</dt><dd>{item.Price?`${item.Currency||'BRL'} ${item.Price}`:'Não informado'}</dd></dl><button className="secondary danger-text" onClick={()=>{if(confirm(`Remover ${item.Title} do catálogo?`))run(async()=>{await DeleteCatalogItem(item.Category);notify('Vínculo removido');await loadCatalog()})}}><Trash2/>Remover vínculo</button></article>):<EmptyState icon={Package} title="Nenhum produto configurado" text="Inicie a configuração pelo WhatsApp do operador."/>}</div></>}
  {tab==='backup'&&backup&&<div className="two-cards"><section className="panel health-card"><div className="section-title"><div><h3>Saúde do motor</h3><span>Diagnóstico local em tempo real</span></div><button className="secondary compact" onClick={loadBackup}><RefreshCw/>Atualizar</button></div><Health ok={backup.DatabaseOK} label="Banco operacional"/><Health ok={backup.Connected} label="Socket WhatsApp"/><Health ok={backup.Authenticated} label="Conta autenticada"/><div className="path-box"><Database/><span>{backup.DataDir}</span></div></section><section className="panel backup-card"><div className="panel-icon"><Archive/></div><h3>Backup verificado</h3><p>Inclui banco, comprovantes e extratos. Nunca inclui sessão WhatsApp ou segredos.</p>{backup.Available?<div className="latest-backup"><CheckCircle2/><div><b>{backup.Path.split(/[\\/]/).pop()}</b><span>{backup.CreatedAt}</span></div></div>:<div className="latest-backup muted"><Archive/><span>Nenhum backup criado ainda.</span></div>}<button className="primary wide" onClick={()=>run(async()=>{setBackup(await RunBackup());notify('Backup criado e verificado')})}><Archive/>Criar backup agora</button></section></div>}
  {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="room-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}><XCircle/></button><span className="section-kicker">QUARTO {selected.Number}</span><h3>Atualizar situação</h3><label className="field"><span>Status</span><select value={selected.Status} onChange={e=>setSelected({...selected,Status:e.target.value})}>{statuses.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label className="field"><span>Quantidade de hóspedes</span><input type="number" min="0" value={selected.Guests} onChange={e=>setSelected({...selected,Guests:e.target.value})}/></label><label className="field"><span>Observação</span><textarea value={selected.Note||''} onChange={e=>setSelected({...selected,Note:e.target.value})}/></label><button className="primary wide" onClick={saveRoom}><Save/>Salvar alterações</button><div className="room-history"><h3><History/>Histórico recente</h3>{history.map((x,i)=><div key={i}><span>{x.OldLabel} → {x.NewLabel}</span><time>{new Date(x.At).toLocaleString('pt-BR')}</time></div>)}</div></section></div>}
  {tab==='bitz'&&bitz&&<BitzPanel bitz={bitz} setBitz={setBitz} save={saveBitz} test={testBitz}/>}
 </div>
}

function BitzPanel({bitz,setBitz,save,test}){return <section className="panel bitz-panel"><div className="section-title"><div><span className="section-kicker">PRÉ-RESERVA SEGURA</span><h3>Integração Bitz</h3><span>O Tino cria a pré-reserva e aguarda a confirmação do aprovador.</span></div><span className={`tag ${bitz.Enabled?'ready':'planned'}`}>{bitz.Enabled?'Ativa':'Inativa'}</span></div><div className="bitz-fields"><label className="field"><span>Endereço</span><input value={bitz.BaseURL||''} readOnly/></label><label className="field"><span>Usuário</span><input autoComplete="off" value={bitz.Username||''} onChange={e=>setBitz({...bitz,Username:e.target.value})}/></label><label className="field"><span>Senha</span><input type="password" autoComplete="new-password" value={bitz.Password||''} onChange={e=>setBitz({...bitz,Password:e.target.value})} placeholder={bitz.PasswordSet?'Senha protegida; deixe vazio para manter':'Informe a senha do Bitz'}/></label><label className="field"><span>CPF operacional do bot</span><input value={bitz.BotCPF||''} onChange={e=>setBitz({...bitz,BotCPF:e.target.value})} placeholder="000.000.000-00"/></label><label className="field"><span>WhatsApp aprovador</span><input value={bitz.ApproverPhone||''} onChange={e=>setBitz({...bitz,ApproverPhone:e.target.value})} placeholder="5573999999999"/></label><label className="field full"><span>Mensagem enviada após aprovação</span><textarea value={bitz.ApprovedText||''} onChange={e=>setBitz({...bitz,ApprovedText:e.target.value})} placeholder="Sua pré-reserva foi confirmada..."/></label></div><div className="bitz-flow">{['Entrar no Bitz','Criar pré-reserva','Avisar aprovador','Confirmar hóspede'].map((step,i)=><div key={step}><b>{i+1}</b><span>{step}</span></div>)}</div><div className="info-strip warning"><ShieldCheck/><span>A senha nunca volta para a interface. O bot somente cria pré-reservas quando o status acima estiver <b>Ativa</b>.</span></div><div className="button-row"><button className="secondary" disabled={!bitz.PasswordSet} onClick={test}><KeyRound/>Testar acesso</button>{bitz.Enabled&&<button className="secondary" onClick={()=>save(false)}>Desativar</button>}<button className="primary" onClick={()=>save(true)}><Save/>Salvar e ativar</button></div></section>}

function Health({ok,label}){return <div className={`health-line ${ok?'ok':'bad'}`}>{ok?<CheckCircle2/>:<XCircle/>}<span>{label}</span><b>{ok?'OK':'Atenção'}</b></div>}
function EmptyState({icon:Icon,title,text}){return <section className="panel empty"><Icon/><b>{title}</b><span>{text}</span></section>}
