import React, {useEffect, useState} from 'react'
import {Bell, Plus, Check, RefreshCw, X} from 'lucide-react'
import {GetBills, AddBill, SetBillStatus, SaveBillReminders} from '../wailsjs/go/main/App'

const money=n=>(Number(n||0)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const date=d=>d.split('-').reverse().join('/')

export default function Bills({notify}) {
 const [rows,setRows]=useState([]),[cfg,setCfg]=useState(null),[busy,setBusy]=useState(false),[filter,setFilter]=useState('OPEN')
 const [draft,setDraft]=useState({Description:'',Amount:'',DueDate:''})
 const run=async fn=>{setBusy(true);try{await fn()}catch(e){notify(String(e),'error')}finally{setBusy(false)}}
 const refresh=async()=>{const view=await GetBills();setRows(view.Bills||[]);setCfg(view.Settings)}
 useEffect(()=>{run(refresh)},[])
 const add=e=>{e.preventDefault();run(async()=>{await AddBill(draft);setDraft({Description:'',Amount:'',DueDate:''});await refresh();notify('Boleto cadastrado')})}
 const change=(id,status)=>run(async()=>{await SetBillStatus(id,status);await refresh();notify(status==='PAID'?'Boleto marcado como pago; lembretes encerrados':'Boleto cancelado')})
 const save=e=>{e.preventDefault();run(async()=>{await SaveBillReminders(cfg);await refresh();notify(cfg.Enabled?'Lembretes ativados':'Lembretes desativados')})}
 const today=new Date().toLocaleDateString('sv-SE',{timeZone:'America/Sao_Paulo'})
 const open=rows.filter(x=>x.Status==='OPEN'),overdue=open.filter(x=>x.DueDate<today)
 return <div className="stack">
  <div className="metric-grid"><section className="metric-card teal"><span>A pagar</span><b>{money(open.reduce((a,x)=>a+x.AmountCents,0))}</b></section><section className="metric-card danger"><span>Vencidos</span><b>{overdue.length}</b></section><section className="metric-card"><span>Vencem hoje</span><b>{open.filter(x=>x.DueDate===today).length}</b></section></div>
  <div className="two-cards">
   <form className="panel stack" onSubmit={add}><h3>Novo boleto</h3><label className="field"><span>Descrição / fornecedor</span><input required maxLength={250} value={draft.Description} onChange={e=>setDraft({...draft,Description:e.target.value})} placeholder="Ex.: Energia elétrica"/></label><label className="field"><span>Valor (R$)</span><input required inputMode="decimal" value={draft.Amount} onChange={e=>setDraft({...draft,Amount:e.target.value})} placeholder="1.250,00"/></label><label className="field"><span>Vencimento</span><input required type="date" value={draft.DueDate} onChange={e=>setDraft({...draft,DueDate:e.target.value})}/></label><button className="primary" disabled={busy}><Plus/>Cadastrar boleto</button><p>O cadastro e a baixa não movimentam o caixa nem realizam pagamentos.</p></form>
   {cfg&&<form className="panel stack" onSubmit={save}><h3><Bell size={18}/> Lembretes no WhatsApp</h3><label><input type="checkbox" checked={cfg.Enabled} onChange={e=>setCfg({...cfg,Enabled:e.target.checked})}/> Ativar lembretes</label><label className="field"><span>WhatsApp que recebe os avisos (com DDI)</span><input required={cfg.Enabled} inputMode="tel" value={cfg.Target} onChange={e=>setCfg({...cfg,Target:e.target.value})} placeholder="5573999999999"/></label><label className="field"><span>Começar quantos dias antes?</span><input type="number" min="0" max="90" required value={cfg.DaysBefore} onChange={e=>setCfg({...cfg,DaysBefore:Number(e.target.value)})}/></label><label className="field"><span>Horário — Brasília</span><input type="time" required value={`${String(cfg.Hour).padStart(2,'0')}:${String(cfg.Minute).padStart(2,'0')}`} onChange={e=>{const [h,m]=e.target.value.split(':').map(Number);setCfg({...cfg,Hour:h,Minute:m})}}/></label><button className="primary" disabled={busy}><Check/>Salvar lembretes</button><p>Um aviso diário por boleto, a partir da antecedência escolhida, incluindo o vencimento e os dias de atraso. Marcar como pago ou cancelar encerra os avisos.</p><p><b>Mantenha o Tino aberto e o WhatsApp conectado.</b> Se ficar desconectado, tenta novamente ao reconectar; ao abrir depois do horário, envia os avisos pendentes do dia.</p></form>}
  </div>
  <section className="panel stack"><div className="section-title"><h3>Seus boletos</h3><div className="button-row"><select aria-label="Filtrar boletos" value={filter} onChange={e=>setFilter(e.target.value)}><option value="OPEN">Pendentes</option><option value="PAID">Pagos</option><option value="CANCELLED">Cancelados</option><option value="ALL">Todos</option></select><button className="secondary" disabled={busy} onClick={()=>run(refresh)}><RefreshCw/>Atualizar</button></div></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Boleto</th><th>Vencimento</th><th>Valor</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{rows.filter(x=>filter==='ALL'||x.Status===filter).map(x=><tr key={x.ID}><td>#{x.ID} — {x.Description}</td><td>{date(x.DueDate)}</td><td>{money(x.AmountCents)}</td><td>{x.Status==='PAID'?'Pago':x.Status==='CANCELLED'?'Cancelado':x.DueDate<today?'Vencido':x.DueDate===today?'Vence hoje':'Pendente'}</td><td>{x.Status==='OPEN'&&<div className="button-row"><button className="secondary compact" disabled={busy} onClick={()=>change(x.ID,'PAID')}><Check/>Marcar como pago</button><button className="secondary compact" disabled={busy} onClick={()=>change(x.ID,'CANCELLED')}><X/>Cancelar</button></div>}</td></tr>)}</tbody></table>{!rows.some(x=>filter==='ALL'||x.Status===filter)&&<p>Nenhum boleto nesta situação.</p>}</div></section>
  <section className="panel"><h3>Também pelo WhatsApp administrativo</h3><p>Cadastro: <code>boleto 20/10/2026 150,00 | Energia</code><br/>Consulta: <code>boletos</code><br/>Baixa: <code>boleto pago 1</code><br/>Cancelamento: <code>cancelar boleto 1</code></p></section>
 </div>
}
